export const MODELS = {
  USER: "user",
  COMPANY_CONTACT: "company-contact",
  FILTER: "filter",
  CONFIGURATION: "configuration",
  EMAILS_SENT: "emails-sent",
  CAMPAIGN: "campaign",
  CAMPAIGN_RUN: "campaign-run",
  SEGMENT: "segment",
  TEMPLATE: "template",
  TEMPLATE_CATEGORY: "template-categories",
  DYNAMIC_TEMPLATE: "dynamic-template",
  CRON_JOB: "cron-job",
  COMPANY: "companies",
  ACCESS_TOKEN: "access-token",
  REFRESH_TOKEN: "refresh-token",
  ROLE: "role",
  SOCIAL_LINK: "social-link",
  ASSET: "asset",
  REFERRAL_CODE: "referral-code",
  REWARD: "reward",
  PLAN: "plan",
  OVERAGE_CONSUMPTION: "overage-comsumption",
  TOPUP: "topup",
  CUSTOMER_REQUESTS: "customer-requests",
  SUPPORT_CHAT_THREAD: "support-chat-thread",
  SUPPORT_CHAT_MESSAGE: "support-chat-message",
  COMPANY_GROUPING: "company-grouping",
  PROJECT: "project",
  BALANCE_DEDUCTION: "balance-deduction",
  UN_SUBSCRIBED_USERS: "un-subscribed-users",
  APP_CONFIG: "app-config",
  CAMPAIGN_RUN_STATS: "campaign-run-stats",
  APPLE_RELAY_EMAIL: "apple-relay-email",
  ATTACHMENT: "attachment",
  NOTIFICATION: "notification",
};

export const CUSTOMER_REQUEST_TYPE = {
  APPLE_RELAY_EMAIL: "apple-relay-email",
  ATTACHMENT: "attachment",
  NOTIFICATION: "notification",
  DEDICATED_IP_ENABLED: "DEDICATED_IP_ENABLED",
  DEDICATED_IP_DISABLED: "DEDICATED_IP_DISABLED",
  DOWNGRADE_PLAN: "DOWNGRADE_PLAN",
  EDIT_CONTACTS_PRIMARY_KEY: "EDIT_CONTACTS_PRIMARY_KEY",
  EDIT_CONTACTS_EMAIL_KEY: "EDIT_CONTACTS_EMAIL_KEY",
  EDIT_CONTACTS_FILTERS: "EDIT_CONTACTS_FILTERS",
};

export const CUSTOMER_REQUEST_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
};

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  BLOCKED: "BLOCKED",
  DELETED: "DELETED",
};

export const USER_KIND = {
  PRIMARY: "PRIMARY",
  SECONDARY: "SECONDARY",
};

export const CAMPAIGN_STATUS = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  DRAFT: "DRAFT",
  ARCHIVED: "ARCHIVED",
};

export const SES_STATUS = {
  HEALTHY: "HEALTHY",
  WARNING: "WARNING",
  RISK: "RISK",
};

export const SOCKET_CHANNELS = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  ADMIN_NOTIFICATION_CREATED: "admin-notification-created",
  SUPPORT_CHAT_JOIN: "support-chat-join",
  SUPPORT_CHAT_LEAVE: "support-chat-leave",
  SUPPORT_CHAT_SEND: "support-chat-send",
  SUPPORT_CHAT_MESSAGE: "support-chat-message",
};

export const ADMIN_NOTIFICATION_TYPES = {
  CUSTOMER_REQUEST_CREATED: "CUSTOMER_REQUEST_CREATED",
  SUPPORT_REQUEST_CREATED: "SUPPORT_REQUEST_CREATED",
  SUPPORT_CHAT_CUSTOMER_MESSAGE: "SUPPORT_CHAT_CUSTOMER_MESSAGE",
};

export const SUPPORT_CHAT_SENDER_TYPE = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;

export const SUPPORT_REQUEST_CATEGORY = {
  GENERAL: "GENERAL",
  BILLING_AND_SUBSCRIPTION: "BILLING_AND_SUBSCRIPTION",
  CAMPAIGNS_AND_SENDING: "CAMPAIGNS_AND_SENDING",
  CONTACTS_AND_AUDIENCE: "CONTACTS_AND_AUDIENCE",
  TEMPLATES_AND_CONTENT: "TEMPLATES_AND_CONTENT",
  INTEGRATIONS: "INTEGRATIONS",
  ACCOUNT_AND_ACCESS: "ACCOUNT_AND_ACCESS",
  TECHNICAL_ISSUE: "TECHNICAL_ISSUE",
  OTHER: "OTHER",
} as const;

export const SUPPORT_REQUEST_CATEGORY_LABELS: Record<string, string> = {
  [SUPPORT_REQUEST_CATEGORY.GENERAL]: "General",
  [SUPPORT_REQUEST_CATEGORY.BILLING_AND_SUBSCRIPTION]: "Billing & Subscription",
  [SUPPORT_REQUEST_CATEGORY.CAMPAIGNS_AND_SENDING]: "Campaigns & Sending",
  [SUPPORT_REQUEST_CATEGORY.CONTACTS_AND_AUDIENCE]: "Contacts & Audience",
  [SUPPORT_REQUEST_CATEGORY.TEMPLATES_AND_CONTENT]: "Templates & Content",
  [SUPPORT_REQUEST_CATEGORY.INTEGRATIONS]: "Integrations",
  [SUPPORT_REQUEST_CATEGORY.ACCOUNT_AND_ACCESS]: "Account & Access",
  [SUPPORT_REQUEST_CATEGORY.TECHNICAL_ISSUE]: "Technical Issue",
  [SUPPORT_REQUEST_CATEGORY.OTHER]: "Other",
};

export const SUPPORT_REQUEST_STATUS = {
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  PENDING_RESOLUTION: "PENDING_RESOLUTION",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
} as const;

export const SUPPORT_REQUEST_STATUS_LABELS: Record<string, string> = {
  [SUPPORT_REQUEST_STATUS.OPEN]: "Open",
  [SUPPORT_REQUEST_STATUS.IN_PROGRESS]: "In progress",
  [SUPPORT_REQUEST_STATUS.PENDING_RESOLUTION]: "Pending customer confirmation",
  [SUPPORT_REQUEST_STATUS.RESOLVED]: "Resolved",
  [SUPPORT_REQUEST_STATUS.CLOSED]: "Closed",
};
